#!/usr/bin/env bash
# Renders the Traefik admin IP allowlist from ADMIN_ALLOWLIST_SOURCE_RANGE.
#
# Traefik's file provider does not expand environment variables, so the allowlist
# is materialised into a dynamic config fragment before the stack starts. Run on
# adm-vm from the repo root with .env.admin already in place.
set -euo pipefail

ENV_FILE="${1:-infra/compose/.env.admin}"
OUT_FILE="${2:-infra/traefik/dynamic/admin-allowlist.yml}"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "error: ${ENV_FILE} not found" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a; source "${ENV_FILE}"; set +a

RANGES="${ADMIN_ALLOWLIST_SOURCE_RANGE:-}"
if [[ -z "${RANGES}" ]]; then
  echo "error: ADMIN_ALLOWLIST_SOURCE_RANGE is empty; refusing to expose the admin host" >&2
  exit 1
fi

{
  echo "# Generated by infra/traefik/render-allowlist.sh — do not edit by hand."
  echo "http:"
  echo "  middlewares:"
  echo "    admin-allowlist:"
  echo "      ipAllowList:"
  echo "        sourceRange:"
  IFS=','
  for range in ${RANGES}; do
    trimmed="$(echo "${range}" | tr -d '[:space:]')"
    [[ -z "${trimmed}" ]] && continue
    echo "          - ${trimmed}"
  done
  unset IFS
  echo "        ipStrategy:"
  echo "          depth: 0"
} > "${OUT_FILE}"

echo "Wrote ${OUT_FILE}:"
cat "${OUT_FILE}"
