# Redis — cache / sessions / rate-limit (no persistence required)
bind 0.0.0.0
protected-mode no
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised no
loglevel notice
databases 16
save ""
appendonly no
maxmemory 512mb
maxmemory-policy allkeys-lru
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
activedefrag yes
hz 20
